version: '3.7'

services:
  nginx:
     image: nginx:1.18-alpine
     ports:
       - "80:80"
     dns: 8.8.8.8
     volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/web:/var/www/html

