version: '3.7'

services:
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes:
      - ./node/app:/usr/src/env/app
      - ./node/data:/data
    dns: 8.8.8.8
    ports:
      - "81:80"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_USER: parser
      DB_NAME: courses
      DB_PASS: Admin123456

volumes:
  db-data: {}
  mysql-data: {}
  redis-data: {}
