version: '3.7'

services:
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis-data:/data
    expose:
      - 6379
    ports:
      - "26379:6379"
    environment:
      REDIS_PASSWORD: kpaHqGrSvJf5TLCU

volumes:
  redis-data: {}
